services:
  mysql:
    image: mysql:latest
    container_name: mysql-database
    environment:
      MYSQL_DATABASE: "nodejs_codejam"
      MYSQL_USER: "bas"
      MYSQL_PASSWORD: "here_we_go"
      MYSQL_ROOT_PASSWORD: here_we_go
    volumes:
      - ./mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-database
    ports:
      - "8080:80"  # Expose phpMyAdmin to public on port 8080
    networks:
      - db-network
    restart: unless-stopped

networks:
  db-network:
    driver: bridge
